<?php

namespace Bundles\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function getArticlesWhereUpdatable() {
     //   $q = $this->getEntityManager()->createQuery("SELECT m FROM BundlesAdminBundle:Menu m WHERE m.editable = 1");
       // return $q->getResult();
    }
}
